### ISSUE TITLE
In def file2matrix()

### ISSUE THREAD

**Issue by ljjks** [apachecn/MachineLearning#143]
When I run "datingDataMat, datingLabels = KNN.file2matrix('datingTestSet2.txt')"
It shows
ValueError: could not convert string to float: 
It makes me confused ,thanks for your answer.

**Comment by chenyyx** [comment]
:) Thank you for your response, the source code of KNN algorithm on the github running on my own computer is normal,and my running environment is Python 2.7.13, you can try to pull the latest source code or check your python version with whether the program is compatible.If you are still confused, you can add our QQ group (629470233) or add my QQ number (190442212) to further solve your confusion ^_^.Thanks again for your reply.

**Comment by chenyyx** [comment]
In the datingTestSet2.txt file, the data is separated by a tab delimiter, and you can view your program and check the program to see whether it is a problem.
