### ISSUE TITLE
pdf 下载下来打不开

### ISSUE THREAD

**Issue by flymenn** [apachecn/MachineLearning#183]
提示“格式错误：不是一个PDF文件或文件已损坏”

**Comment by chenyyx** [comment]
大佬，我这儿刚才重新都下载了一次，这几本pdf书籍都是可以打开的，没有提示错误。大佬你看看是不是下载的时候网络出现了问题或者说出现了一些小波动，这有可能导致下载下来的pdf格式损坏。另外，可以加我们的QQ群，群文件里有相关的资源。
