### ISSUE TITLE
k-means工作流程 翻译错字

### ISSUE THREAD

**Issue by yqiang777** [apachecn/MachineLearning#252]
第十章中K-Means 工作流程
原文

    首先, 随机确定 K 个初始点作为质心（不是数据中的点）.
    然后将数据集中的每个点分配到一个簇中, 具体来讲, 就是为每个点找到距其最近的质心, 并将其分配该质心所对应的簇. 这一步完成之后, 每个簇的质心更新为该簇说有点的平均值.

应该更改为

    首先, 随机确定 K 个初始点作为质心（不是数据中的点）.
    然后将数据集中的每个点分配到一个簇中, 具体来讲, 就是为每个点找到距其最近的质心, 并将其分配该质心所对应的簇. 这一步完成之后, 每个簇的质心更新为该簇所有点的平均值.

将“说有”更改为“所有”。

**Comment by jiangzhonglian** [comment]
庭哥，你看看这边的内容

**Comment by wangyangting** [comment]
感谢提醒，已修改！←_←
