### ISSUE TITLE
第12章FP-Growth算法的一个bug（疑似）

### ISSUE THREAD

**Issue by lonelam** [apachecn/MachineLearning#256]
```
def createTree(dataSet, minSup=1):


...


            orderedItems = [v[0] for v in sorted(localD.items(), key=lambda p: p[1], reverse=True)]


...
```

这里单以localD的值作为key进行排序，当两个项计数值一样时，会产生不确定的结果，比如('c',3) == ('d',3) 
但是不知道为什么在python2没跑出错
移植python3后会产生随机结果
fix:
```
orderedItems = [v[0] for v in sorted(localD.items(), key=lambda p: (p[1],p[0]), reverse=True)]
```

**Comment by jiangzhonglian** [comment]
@mikechengwei   威哥，有兄弟给你提了一个bug。请review一下

**Comment by mikechengwei** [comment]
@lonelam 这里我们是按照FP-growth出现的支持度来进行排序，支持度一样的时候，顺序是无所谓的。不需要将值和支持度一起排序。
总结就是说当支持度一样的时候，随机结果是正常的。

**Comment by lonelam** [comment]
@mikechengwei 我的理解是这样，FP-Tree是一棵把数据集合按照一定顺序序列化以后的Trie树，而apriori原理之所以在FP-Tree上成立

**Comment by mikechengwei** [comment]
那个首先 
a[2]-b[2]
b[1]-a[1]
是得不出来的，因为在筛选出支持度大于等于3的项集后，所有的数据集会根据项目集重新排序的。
所以最终都是['a','b']的顺序。

第二如果我有
a[2]-b[2]
b[1]-a[1]
这样一棵FP树，我拿出的a的条件FP树，那只是b[1]
同理b的条件FP树是a[2]。

我觉得你可以看下我们的教学文档和视频。理解下FP树是如何构造的。
