### ISSUE TITLE
第10章 K-均值聚类算法中的一个BUG

### ISSUE THREAD

**Issue by scnb** [apachecn/MachineLearning#262]
在第10章开头的loadDataSet()函数中，使用了map函数来处理数据，该map函数在python2会直接返回一个list，但是在python3中只返回该列表的地址，想要得到该list，需要用list(map())来强制转换。

**Comment by scnb** [comment]
@wangyangting

**Comment by scnb** [comment]
@jiangzhonglian

**Comment by jiangzhonglian** [comment]
@xuzhaoqing   昭清大佬，这边对 kmearn 提交了一个bug,  辛苦大家看看
