### ISSUE TITLE
斗胆指一下注释中的一个小错误

### ISSUE THREAD

**Issue by ZhaoLizz** [apachecn/MachineLearning#272]
https://github.com/apachecn/MachineLearning/blob/python-3.6/src/python/3.DecisionTree/DecisionTree.py  
141行的注释 `# retDataSet = [data for data in dataSet for i, v in enumerate(data) if i == axis and v == value]` 这里的 `i == axis`是不是应该改为`i == index`?

**Comment by jiangzhonglian** [comment]
@jingwangfei   好像这个注释的地方，是写错呢？ 因该是 index 不是 axis

**Comment by ZhaoLizz** [comment]
对我就是这个意思,上面函数定义时写的index而不是axis,把注释里面的axis改成index就好了吧

**Comment by jingwangfei** [comment]
谢谢， 确实， 我修改过来了。
