### ISSUE TITLE
图像压缩

### ISSUE THREAD

**Issue by cjr0106** [apachecn/MachineLearning#347]
在使用SVD对图像压缩的时候，为什么最后32*32显示的全是数字“0”，

**Comment by jiangzhonglian** [comment]
？？？ 你可以写仔细一点吗 ？？？

**Comment by cjr0106** [comment]
在《machine learning for action》这本书中，第十四章关于PCA算法中，最后一个例子是将0_5.txt文件中的32*32的图像压缩处理，这个图像是由0和1显示的数字“0”，但是在按照书上的代码写进去之后，本应该处理完后，还是由数字0和数字1显示的数字“0”，但是，最后结果全是数字0

**Comment by jiangzhonglian** [comment]
为什么不试试我们写的代码呢？

**Comment by cjr0106** [comment]
但是我也想知道 那个为啥就错了 ，我把书上的和您的对比了，感觉没太大的差别，就是不知道为啥呢？
您方便留个方式吗，我可以把这个发给您，您看一下？
