### ISSUE TITLE
第4章 基于概率论的分类方法：朴素贝叶斯其中一个问题

### ISSUE THREAD

**Issue by TronYY** [apachecn/MachineLearning#363]
对朴素贝叶斯分类器训练函数的代码块中：
``p1Denom += sum(trainMatrix[i])``和``p0Denom``为何不是每次加一

**Comment by wnma3mz** [comment]
应该是统计单词总个数，而不是文档数。
已在QQ详细回复

**Comment by TronYY** [comment]
还没有解释好，我给了一个示例。
![issue](https://user-images.githubusercontent.com/24478375/38989900-e825c346-440a-11e8-879b-e8fa05be7713.jpg)

**Comment by jiangzhonglian** [comment]
在辱骂的时候：（正常也一回事）
特征（A/B/C）/总次数（一样对吧，都） = A/B/C的平均概率（不是A/B/C的正负概率）
特征（A/B/C）/各个特征值的加和   = A/B/C的正负概率（根据每个特征值的和是不一样的）

我这样解释明白？？？

**Comment by TronYY** [comment]
不明白
