### ISSUE TITLE
贝叶斯问题

### ISSUE THREAD

**Issue by zsmjhtn** [apachecn/MachineLearning#377]
demo里的训练集的数据都是相同的长度。请问如果训练集的数据是混乱的，长短不一。这样去训练数据，感觉矩阵处理会比较麻烦。所以请问，训练集的数据长度相同，格式一致，这是必须要遵守的基本要求吗？还是说，是为了出于demo显示的考虑，demo处理数据方便，所以将真实数据“理想化”处理了？谢谢

**Comment by jiangzhonglian** [comment]
你没看我们 朴素贝叶斯的 项目么？？ 请先看一下，你的疑惑就没来
