### ISSUE TITLE
真相（group-true）:真正存在的潜在规律 是否存在拼写错误

### ISSUE THREAD

**Issue by xealml** [apachecn/MachineLearning#410]
https://github.com/apachecn/MachineLearning/blob/master/docs/1.%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E5%9F%BA%E7%A1%80.md中的有一行
真相（group-true）:真正存在的潜在规律

**Comment by chenyyx** [comment]
感谢指出，应该是 ground-truth
