### ISSUE TITLE
About coding

### ISSUE THREAD

**Issue by highfei2011** [apachecn/MachineLearning#8]
Must be written in python? Thank you！

**Comment by highfei2011** [comment]
Can I use idea to develop?

**Comment by highfei2011** [comment]
and How to become a contributor to the project? Thank you.

**Comment by apachecn** [comment]
1.为了统一教材资料，所以选择了python
2.可以使用任何idea去开发（但你idea的配置文件不用上传到git上面）
3.you can see this page( 1》GitHub操作步骤 ): http://www.apache.wiki/display/Team/2017-02-27

Good luck

**Comment by apachecn** [comment]
1.为了统一教材资料，所以选择了python
2.可以使用任何idea去开发（但你idea的配置文件不用上传到git上面）
3.you can see this page( 1》GitHub操作步骤 ): http://www.apache.wiki/display/Team/2017-02-27

Good luck

**Comment by highfei2011** [comment]
Thanks
